### ISSUE TITLE
Soldiers cosmetic appearances randomize whenever equiping prototype plate or scavenged kevlar.

### ISSUE THREAD

**Issue by ciasputnikmonroe** [WOTCStrategyOverhaul/PrototypeArmoury#14]
Whenever I equip a soldier with the prototype plate or scavenged kevlar I've received from scans, the appearance cosmetics of the soldier randomize. If I take the armor off and put it back on the appearance randomizes again. The default kevlar does this as well, the only armor that doesn't seem to randomize appearance when equipped is the resistance kevlar. The resistance kevlar seems to remember appearance and reload it each time it's unequipped and re-equipped.

**Comment by WilleBack** [comment]
Can confirm this also happens with the tier 3 experimental power armor. In my case, a soldier equipped with the affected armors always spawns without a torso.

From what I can tell, the game is not loading torsos properly. During squad loadout, if the first thing I do is equip one of the bugged armors and go to customize the soldier, the options for torsos, arms, and left and right arms do not appear at all. 

If I customize other armors, then equip a soldier with the affected armor and customize them, the options I get seem to be a subset of the options I had when customizing the previous soldier, up to and including getting advent disguise and WAR suit customizations on prototype field plate.

**Comment by WilleBack** [comment]
Additional clarification from playing today:

It is enough to equip someone with a different armor than the one they were wearing to get the customization options to show up for a soldier wearing an affected armor. Before this, the soldier only has options available that are not dependent on armor or armor set, like tattoos and tattoo color.

**Comment by MrCloista** [comment]
I have the fix.

XComContent.ini for Prototype Armoury is missing : [XComGame.X2BodyPartTemplateManager]  at the start of the file
