### ISSUE TITLE
Rework template removal

### ISSUE THREAD

**Issue by Xymanek** [WOTCStrategyOverhaul/PrototypeArmoury#4]
Currently we remove templates using a bunch of template-specific changes to it, such as setting always-failing requirements, insane prices, etc.

A potential improvement would be using `Template.RemoveTemplateAvailablility(BITFIELD_GAMEAREA_ALL);` on all difficulty variants. This will render it inaccessible outside of `FindDataTemplateAllDifficulties`, effectively removing it.

If this works, we should also apply same approach to whatever template mods CI has (that will not get moved here)

**Comment by cannonfodder1** [comment]
The approach outlined above does not appear to work, as when an existing campaign save is loaded and GiveTech console command run, the schematics appear alongside singlebuilt items.

**Comment by Xymanek** [comment]
> when an existing campaign save is loaded

Did you try a new ~~save~~ campaign?

**Comment by cannonfodder1** [comment]
> Did you try a new ~save~ campaign?

Just did, without success

**Comment by Xymanek** [comment]
Ok, then let's give up on this idea for now for sake of not wasting time
