### ISSUE TITLE
Modded items rely on vanilla schematics to unlock

### ISSUE THREAD

**Issue by cannonfodder1** [WOTCStrategyOverhaul/PrototypeArmoury#7]
We should mark the schematic as complete when you build the first piece of a new type of item, so that all modded infinite items tied to the schematic are unlocked as well.

**Comment by cannonfodder1** [comment]
New plan is to alter all of the items which have their CreatorTemplateName set to a schematic so that it’s set to the singlebuilt item instead. Mods that do not have bridges that rely on the schematics should theoretically be unlocked once the player builds the first item that was previously associated with that schematic. Needs investigation and testing.

**Comment by Xymanek** [comment]
Not a big fan of that plan tbh. It relies a lot on assumptions which might not be true for some mods. Additionally, I'm generally against "magic" behaviours - they are confusing to debug, especially with other mods piled up on top.

I think it's better to just say "need bridges" and end this issue there
